# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Cem Asma
tagline:             'dev.cemas@gmail.com'
description:         'Ana odağı teknoloji ağırlıklı olmak üzere, Cem Asma'nın kişisel blogu.'
url:                 https://cemasma.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Cem Asma
  url:               https://github.com/cemasma
  email:             dev.cemas@gmail.com

# Custom vars
version:             1.0.0
